// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFEsSX177xKECKeJNB41ofUqCvX_Xi78o',
    appId: '1:554740889018:web:4d6e6c961023e2c0235983',
    messagingSenderId: '554740889018',
    projectId: 'instagram-990ac',
    authDomain: 'instagram-990ac.firebaseapp.com',
    storageBucket: 'instagram-990ac.appspot.com',
    measurementId: 'G-XR2R2RFG84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzJf9JydFs45HxHBpyykyeG24kWxzgleU',
    appId: '1:554740889018:android:d50d4581ccbb0a37235983',
    messagingSenderId: '554740889018',
    projectId: 'instagram-990ac',
    storageBucket: 'instagram-990ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD75qC2aznl_JbhOaOJxPwdn4A7cbWWI4Q',
    appId: '1:554740889018:ios:c365a70dbb85cfbf235983',
    messagingSenderId: '554740889018',
    projectId: 'instagram-990ac',
    storageBucket: 'instagram-990ac.appspot.com',
    iosClientId: '554740889018-q62a9hl5mpbar4e7pac4lr7b9bvjg501.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD75qC2aznl_JbhOaOJxPwdn4A7cbWWI4Q',
    appId: '1:554740889018:ios:c365a70dbb85cfbf235983',
    messagingSenderId: '554740889018',
    projectId: 'instagram-990ac',
    storageBucket: 'instagram-990ac.appspot.com',
    iosClientId: '554740889018-q62a9hl5mpbar4e7pac4lr7b9bvjg501.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
